language: node_js
node_js: 
  - '8.9.0'

# S: Build Lifecycle
install:
  - npm install
  - git submodule init
  - git submodule update


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "razor"
  - git config user.email "baozhejun@outlook.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${blog_token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/OckhamRazor/blog.git